### ISSUE TITLE
SSL Connexion issue with PazPar2 / GNUTls

### ISSUE THREAD

**Issue by gjactat** [indexdata/pazpar2#27]
Hello,
I try to query the following SRU server through PazPar2 : https://journals.sagepub.com/action/sru

The connection fails with the following log :
`15:51:02-24/05 pazpar2 [warn] Session 1: https://journals.sagepub.com:443/action/sru: Error Connect failed (https://journals.sagepub.com:443/action/sru)
`

The very same connexion succeeds if done through a fiddler Proxy (with pz:proxy). In this case, Fiddler acts as a "Man in the Middle" and becomes the new initiator of the connexion (which is done right by Fiddler).
I'm using the following versions of components :

- PazPar2 1.14.0 (windows build)
- Yaz 5.30.2
- GnuTls 3.6.13

Hint : A connexion test directly performed with gnutls-cli is successfull though on the same host.
Hope you will be able to reproduce this behaviour..

Guillaume

**Comment by gjactat** [comment]
Hello,
I've been investigating a but further and I've notice that the TLS HandShake fails with this particular server because the "ServerName" property is not specified through PazPar2/Yaz.
Whereas GnuTLS and Fiddler fill this property (and hence manage to successfully complete the TLS handshake).
I've patched YAZ locally to invoke "**gnutls_server_name_set**" before each GnuTLS hanshake and it worked... I don't know Yaz/C right enough to do this right though (my patch currently use a hard coded string for the sake of simplicity).

See details here : https://www.gnutls.org/manual/gnutls.html#Server-name-indication

Hope this helps,
Guillaume

**Comment by adamdickmeiss** [comment]
Thx for looking into this.. Part of YAZ now.. https://github.com/indexdata/yaz/commit/fc42d1dcf21dfa82c73ec2aee8f98116fe15a5b7
